package com.ilunyu.lunyu.ui.theme

import androidx.compose.ui.graphics.Color

// Brand Seed Colors (from Flutter LunyuTheme)
val SeedTeal = Color(0xFF315E5A)
val Vermilion = Color(0xFF8F3C2F)
val Ink = Color(0xFF1A1C1B)

// Light Theme Colors (100% exact match with Flutter LunyuTheme.light())
val LightPrimary = Color(0xFF006A64)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF9DF2E9)
val LightOnPrimaryContainer = Color(0xFF00504B)
val LightSecondary = Color(0xFF4A6360)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E4)
val LightOnSecondaryContainer = Color(0xFF324B49)
val LightTertiary = Vermilion // 0xFF8F3C2F
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF8DDD7)
val LightOnTertiaryContainer = Color(0xFF3B0904)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)
val LightSurface = Color(0xFFFCFCFC)
val LightOnSurface = Ink // 0xFF1A1C1B
val LightSurfaceDim = Color(0xFFDADCDC)
val LightSurfaceBright = Color(0xFFFCFCFC)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF2F4F4)
val LightSurfaceContainer = Color(0xFFECEEEE)
val LightSurfaceContainerHigh = Color(0xFFE5E7E7)
val LightSurfaceContainerHighest = Color(0xFFDDE0DF)
val LightSurfaceVariant = Color(0xFFECEEEE)
val LightOnSurfaceVariant = Color(0xFF454847)
val LightOutline = Color(0xFF757877)
val LightOutlineVariant = Color(0xFFC5C8C7)
val LightInverseSurface = Color(0xFF2F3130)
val LightInverseOnSurface = Color(0xFFF1F1F1)
val LightInversePrimary = Color(0xFF81D5CD)

// Dark Theme Colors (100% exact match with Flutter LunyuTheme.dark())
val DarkPrimary = Color(0xFF81D5CD)
val DarkOnPrimary = Color(0xFF003734)
val DarkPrimaryContainer = Color(0xFF00504B)
val DarkOnPrimaryContainer = Color(0xFF9DF2E9)
val DarkSecondary = Color(0xFFB0CCC8)
val DarkOnSecondary = Color(0xFF1C3532)
val DarkSecondaryContainer = Color(0xFF324B49)
val DarkOnSecondaryContainer = Color(0xFFCCE8E4)
val DarkTertiary = Color(0xFFFFB4A5)
val DarkOnTertiary = Color(0xFF571E16)
val DarkTertiaryContainer = Color(0xFF642B25)
val DarkOnTertiaryContainer = Color(0xFFFFDAD4)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkSurface = Color(0xFF101212)
val DarkOnSurface = Color(0xFFE2E3E2)
val DarkSurfaceDim = Color(0xFF101212)
val DarkSurfaceBright = Color(0xFF363838)
val DarkSurfaceContainerLowest = Color(0xFF0B0D0D)
val DarkSurfaceContainerLow = Color(0xFF181A1A)
val DarkSurfaceContainer = Color(0xFF1E2020)
val DarkSurfaceContainerHigh = Color(0xFF282A2A)
val DarkSurfaceContainerHighest = Color(0xFF333535)
val DarkSurfaceVariant = Color(0xFF1E2020)
val DarkOnSurfaceVariant = Color(0xFFC4C7C6)
val DarkOutline = Color(0xFF8E9190)
val DarkOutlineVariant = Color(0xFF454847)
val DarkInverseSurface = Color(0xFFE2E3E2)
val DarkInverseOnSurface = Color(0xFF2E3030)
val DarkInversePrimary = Color(0xFF006A64)
